fix AppImage unexpanded variables logic
Closes #150

Co-authored-by: google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>

diff --git a/templates/github-appimage.tmpl b/templates/github-appimage.tmpl
--- a/templates/github-appimage.tmpl
+++ b/templates/github-appimage.tmpl
@@ -159,7 +159,7 @@ jobs:
                 echo '	fi'
   [[ else ]]
                 echo '	if use [[ $keyword ]]; then'
-                echo "		cp \"${DISTDIR}/${P}-${{ env.[[ join (filterEmpty $pname "release_name" $keyword) "_" ]] }}\" \"${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}\"  || die \"Can't copy downloaded file\""
+                echo "		cp \"\${DISTDIR}/\${P}-${{ env.[[ join (filterEmpty $pname "release_name" $keyword) "_" ]] }}\" \"${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}\"  || die \"Can't copy downloaded file\""
                 echo '	fi'
   [[ end ]]
 [[ end ]]
