Add AppImage extraction steps

diff --git a/templates/github-appimage.tmpl b/templates/github-appimage.tmpl
--- a/templates/github-appimage.tmpl
+++ b/templates/github-appimage.tmpl
@@ -1,240 +1,94 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder [[.Version]] [[.Type]] [[.ConfigFile]] [[.Now]]
+# Generated by arrans_binary_overlay_builder
+EAPI=8
+DESCRIPTION="[[ .Description ]]"
+HOMEPAGE="[[ .Homepage ]]"
+LICENSE="[[ .License ]]"
+SLOT="0"
+KEYWORDS="[[ .MaskedKeywords ]]"
+IUSE=""
+DEPEND=""
+RDEPEND="[[ range $i, $dep := .Dependencies ]][[ $dep ]] [[ end ]]"
+S="${WORKDIR}"
+RESTRICT="strip"
+[[ if .HasDesktopFile ]]
+inherit xdg-utils
+[[ end ]]
 
-name: [[ .WorkflowName ]]
+SRC_URI="
+[[ range $er := .ExternalResources ]]
+  https://github.com/[[ $.GithubOwner ]]/[[ $.GithubRepo ]]/releases/download/[[ $.Tag ]]/[[ $er.ReleaseFilename | ebuildvardoublequoted ]]
+[[ end ]]
+"
 
-permissions:
-  contents: write
+src_unpack() {
+[[ range $pname, $prog := .Programs ]]
+  [[ range $keyword, $binary := $prog.Binary ]]
+    cp "${DISTDIR}/[[ index $binary 0 | ebuildvardoublequoted ]]" "[[ $prog.InstalledFilename ]]" || die "Can't copy archive file"
+    chmod a+x "[[ $prog.InstalledFilename ]]" || die "Can't chmod archive file"
+  [[ end ]]
+  [[ if $prog.HasDesktopFile ]]
+    "./[[ $prog.InstalledFilename ]]" --appimage-extract "[[ $prog.DesktopFile ]]" || die "Failed to extract .desktop from appimage"
+  [[ end ]]
+  [[ range $icon := $prog.Icons ]]
+    [[ if eq $icon "hicolor-apps" ]]
+    "./[[ $prog.InstalledFilename ]]" --appimage-extract "usr/share/icons" || die "Failed to extract hicolor icons from app image"
+    [[ else if eq $icon "pixmaps" ]]
+    "./[[ $prog.InstalledFilename ]]" --appimage-extract "usr/share/pixmaps" || die "Failed to extract pixmaps icons from app image"
+    [[ else if eq $icon "root" ]]
+    "./[[ $prog.InstalledFilename ]]" --appimage-extract "*.png" || die "Failed to extract root icons from app image"
+    [[ end ]]
+  [[ end ]]
+[[ end ]]
+}
 
-on:
-  schedule:
-    - cron: '[[ .Cron ]]'
-  workflow_dispatch:
-  push:
-    paths:
-      - '.github/workflows/[[ .WorkflowFileName ]]'
+src_prepare() {
+[[ if .HasDesktopFile ]]
+[[ range $pname, $prog := .Programs ]]
+[[ if $prog.HasDesktopFile ]]
+  sed -i 's:^Exec=.*:Exec=/opt/bin/[[ $prog.InstalledFilename ]]:' "squashfs-root/[[ $prog.DesktopFile ]]"
+[[ end ]]
+[[ end ]]
+[[ end ]]
+[[ range $pname, $prog := .Programs ]]
+[[ range $icon := $prog.Icons ]]
+[[ if eq $icon "hicolor-apps" ]]
+  find squashfs-root -type f \( -name index.theme -or -name icon-theme.cache \) -exec rm {} \;
+  find squashfs-root -type d -exec rmdir -p --ignore-fail-on-non-empty {} \;
+[[ end ]]
+[[ end ]]
+[[ end ]]
+  eapply_user
+}
 
-concurrency:
-  group: ci-${{ github.ref }}
-  cancel-in-progress: false
+src_install() {
+    exeinto /opt/bin
+[[ range $pname, $prog := .Programs ]]
+    doexe "[[ $prog.InstalledFilename ]]" || die "Failed to install AppImage"
+[[ end ]]
+[[ if .HasDesktopFile ]]
+    insinto /usr/share/applications
+[[ range $pname, $prog := .Programs ]]
+    doins "squashfs-root/[[ $prog.DesktopFile ]]" || die "Failed to install desktop file"
+[[ end ]]
+[[ end ]]
+[[ range $pname, $prog := .Programs ]]
+[[ range $icon := $prog.Icons ]]
+[[ if eq $icon "hicolor-apps" ]]
+    insinto /usr/share/icons
+    doins -r squashfs-root/usr/share/icons/hicolor || die "Failed to install icons"
+[[ else if eq $icon "pixmaps" ]]
+    insinto /usr/share/pixmaps
+    doins squashfs-root/usr/share/pixmaps/*.png || die "Failed to install icons"
+[[ else if eq $icon "root" ]]
+    insinto /usr/share/pixmaps
+    doins squashfs-root/*.png || die "Failed to install icons"
+[[ end ]]
+[[ end ]]
+[[ end ]]
+}
 
-env:
-  ecn: [[ .Category ]]
-  epn: [[ .PackageName ]]
-  description: [[ .Description | quoteStr ]]
-  homepage: [[ .Homepage  | quoteStr ]]
-  github_owner: [[ .GithubOwner ]]
-  github_repo: [[ .GithubRepo ]]
-  keywords: [[ .MaskedKeywords ]]
-  workflow_filename: [[ .WorkflowFileName ]]
-  [[- range $pname, $prog := .Programs ]]
-  [[- if $prog.HasDesktopFile ]]
-  [[ join (filterEmpty $pname "desktop_file" ) "_" ]]: '[[ $prog.DesktopFile ]]'
-  [[- end ]]
-  [[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]]: '[[ $prog.InstalledFilename ]]'
-  [[- range $keyword, $binary := $prog.Binary ]]
-  [[- if gt (len $binary) 2 ]]
-  [[ join (filterEmpty $pname "appimage_archived_name" $keyword) "_" ]]: '[[ index $binary 1 ]]'
-  [[- end ]]
-  [[ join (filterEmpty $pname "release_name" $keyword) "_" ]]: '[[ index $binary 0 | ebuildvardoublequoted ]]'
-  [[- end ]]
-  [[- end ]]
-
-jobs:
-  check-and-create-ebuild:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      - name: Set up Git
-        run: |
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-
-      - name: Install required tools
-        run: |
-            sudo apt-get update
-            sudo apt-get install -y wget jq coreutils
-            url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
-            echo "$url"
-            wget "${url}" -O /tmp/g2.deb
-            sudo dpkg -i /tmp/g2.deb
-            rm /tmp/g2.deb
-
-      - name: Process each release
-        id: process_releases
-        run: |
-          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
-          mkdir -p $ebuild_dir
-          declare -A releaseTypes=()
-          tags=$(curl -s  --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[].tag_name')
-[[- if .WorkaroundSemanticVersionWithoutV ]]
-          for tag in $tags; do
-            version="${tag}"
-[[- else ]]
-          for tag in $tags; do
-            version="${tag#[[- .WorkaroundTagPrefix ]]v}"
-            if [ "${version}" = "${tag}" ]; then
-                echo "$version == $tag so there is no [[ .WorkaroundTagPrefix ]]v removed skipping"
-                continue
-            fi
-[[- end ]]
-            originalVersion="${version}"
-[[- if .WorkaroundSemanticVersionPrereleaseHack1 ]]
-            version="$(echo "${version}" | sed 's/^\([0-9]\+\(\.[0-9]\+\)*\)\(-r[0-9]*\)\?\([-_]\(alpha\|beta\|rc\|p\)\(\|\.\?\([0-9]\+\)\)\)$/\1_\5\3\7/')"
-[[- end ]]
-            if ! echo "${version}" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
-                echo "version: $version doesn't match regexp";
-                continue;
-            fi
-            releaseType="$(echo "${version}" | sed -n 's/^[^_]\+_\(alpha\|beta\|rc\|p[0-9]*\).*$/\1/p')"
-            if [[`[[ ! -v releaseTypes[${releaseType:=release}] ]]`]]; then
-                releaseTypes[${releaseType:=release}]="$version"
-            else
-                echo "Already have a newier ${releaseType:=release} release: ${releaseTypes[${releaseType:=release}]}"
-                continue
-            fi
-            ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}.ebuild"
-            if [ ! -f "$ebuild_file" ]; then
-
-              {
-                echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/${{ env.workflow_filename }}'
-                echo 'EAPI=8'
-                echo "DESCRIPTION=\"${{ env.description }}\""
-                echo "HOMEPAGE=\"${{ env.homepage }}\""
-                echo 'LICENSE="MIT"'
-                echo 'SLOT="0"'
-                echo 'KEYWORDS="${{ env.keywords }}"'
-                echo 'IUSE=""'
-                echo 'DEPEND=""'
-                echo 'RDEPEND="[[range $i, $dep := .Dependencies]][[$dep]] [[end]]"'
-                echo 'S="${WORKDIR}"'
-                echo 'RESTRICT="strip"'
-[[- if .HasDesktopFile ]]
-                echo ''
-                echo "inherit xdg-utils"
-[[- end ]]
-                echo ''
-                echo 'SRC_URI="'
-[[- range $releaseFilename, $externalResource := .ExternalResources ]]
-    [[- if $.WorkaroundSemanticVersionPrereleaseHack1 ]]
-                echo "  [[ $externalResource.Keyword ]]? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/[[ $releaseFilename | ebuildvardoublequotedSemanticVersionPrereleaseHack1 ]] -> \${P}-[[ $releaseFilename  | ebuildvardoublequoted ]] )"
-    [[- else ]]
-                echo "  [[ $externalResource.Keyword ]]? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/[[ $releaseFilename | ebuildvardoublequoted ]] -> \${P}-[[ $releaseFilename  | ebuildvardoublequoted ]] )"
-    [[- end ]]
-[[- end ]]
-                echo '"'
-                echo ''
-                echo 'src_unpack() {'
-[[- range $releaseFilename, $externalResource := .ExternalResources ]]
-  [[- if $externalResource.Archived ]]
-                echo '  if use [[ $externalResource.Keyword ]]; then'
-                echo "    unpack \"\${DISTDIR}/\${P}-[[ $releaseFilename | ebuildvardoublequoted ]]\" || die \"Can't unpack archive file\""
-                echo '  fi'
-  [[- end ]]
-[[- end ]]
-[[- range $pname, $prog := .Programs ]]
-[[- range $keyword, $binary := $prog.Binary ]]
-  [[- if gt (len $binary) 2 ]]
-                echo '  if use [[ $keyword ]]; then'
-                echo "    mv \"${{ env.[[ join (filterEmpty $pname "appimage_archived_name" $keyword) "_" ]] }}\" \"${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}\"  || die \"Can't move archived file\""
-                echo '  fi'
-  [[- else ]]
-                echo '  if use [[ $keyword ]]; then'
-                echo "    cp \"\${DISTDIR}/\${P}-${{ env.[[ join (filterEmpty $pname "release_name" $keyword) "_" ]] }}\" \"${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}\"  || die \"Can't copy downloaded file\""
-                echo '  fi'
-  [[- end ]]
-[[- end ]]
-                echo '  chmod a+x "${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}"  || die "Can'\''t chmod archive file"'
-[[- if $prog.HasDesktopFile ]]
-                echo '  "./${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}" --appimage-extract "${{ env.[[ join (filterEmpty $pname "desktop_file" ) "_" ]] }}" || die "Failed to extract .desktop from appimage"'
-[[- end ]]
-[[- range $i, $icon := $prog.Icons ]]
-  [[- if eq $icon "hicolor-apps" ]]
-                echo '  "./${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}" --appimage-extract "usr/share/icons" || die "Failed to extract hicolor icons from app image"'
-  [[- end ]]
-  [[- if eq $icon "pixmaps" ]]
-                echo '  "./${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}" --appimage-extract "usr/share/pixmaps" || die "Failed to extract pixmaps icons from app image"'
-  [[- end ]]
-  [[- if eq $icon "root" ]]
-                echo '  "./${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}" --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
-  [[- end ]]
-[[- end ]]
-[[- end ]]
-                echo '}'
-                echo ''
-                echo 'src_prepare() {'
-[[- if .HasDesktopFile ]]
-  [[- range $pname, $prog := .Programs ]]
-    [[- if $prog.HasDesktopFile ]]
-                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}:' 'squashfs-root/${{ env.[[ join (filterEmpty $pname "desktop_file" ) "_" ]] }}'"
-    [[- end ]]
-  [[- end ]]
-[[- end ]]
-[[- range $pname, $prog := .Programs ]]
-  [[- range $i, $icon := $prog.Icons ]]
-    [[- if eq $icon "hicolor-apps" ]]
-                echo "  find squashfs-root -type f \( -name index.theme -or -name icon-theme.cache \) -exec rm {} \; "
-                echo "  find squashfs-root -type d -exec rmdir -p --ignore-fail-on-non-empty {} \; "
-    [[- end ]]
-  [[- end ]]
-[[- end ]]
-                echo '  eapply_user'
-                echo '}'
-                echo ''
-                echo 'src_install() {'
-                echo '  exeinto /opt/bin'
-[[- range $pname, $prog := .Programs ]]
-                echo '  doexe "${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}" || die "Failed to install AppImage"'
-[[- end ]]
-[[- if .HasDesktopFile ]]
-                echo '  insinto /usr/share/applications'
-  [[- range $pname, $prog := .Programs ]]
-                echo '  doins "squashfs-root/${{ env.[[ join (filterEmpty $pname "desktop_file" ) "_" ]] }}" || die "Failed to install desktop file"'
-  [[- end ]]
-[[- end ]]
-[[- range $pname, $prog := .Programs ]]
-  [[- range $i, $icon := $prog.Icons ]]
-    [[- if eq $icon "hicolor-apps" ]]
-                echo '  insinto /usr/share/icons'
-                echo '  doins -r squashfs-root/usr/share/icons/hicolor || die "Failed to install icons"'
-    [[- else if eq $icon "pixmaps" ]]
-                echo '  insinto /usr/share/pixmaps'
-                echo '  doins squashfs-root/usr/share/pixmaps/*.png || die "Failed to install icons"'
-    [[- else if eq $icon "root" ]]
-                echo '  insinto /usr/share/pixmaps'
-                echo '  doins squashfs-root/*.png || die "Failed to install icons"'
-    [[- end ]]
-  [[- end ]]
-[[- end ]]
-                echo '}'
-                echo ""
-[[- if .HasDesktopFile ]]
-                echo "pkg_postinst() {"
-                echo "  xdg_desktop_database_update"
-                echo "}"
-                echo ""
-[[- end ]]
-              } > $ebuild_file
-
-              # Manifest generation
-[[ range $releaseFilename, $externalResource := .ExternalResources ]] 
-    [[- if $.WorkaroundSemanticVersionPrereleaseHack1 ]]
-              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/[[ $releaseFilename | ebuildvardoublequotedSemanticVersionPrereleaseHack1 ]]" "${{ env.epn }}-${version}-[[ $releaseFilename | actionvardoublequoted ]]" "${ebuild_dir}/Manifest"
-    [[- else ]]
-              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/[[ $releaseFilename | actionvardoublequoted ]]" "${{ env.epn }}-${version}-[[ $releaseFilename | actionvardoublequoted ]]" "${ebuild_dir}/Manifest"
-    [[- end ]]
-
-[[- end ]]
-              echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
-            fi
-          done
-
-      - name: Commit and push changes
-        run: |
-          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
-          git add ./${ebuild_dir}
-          git commit -m "Add ebuilds for new ${{ env.epn }} releases tag ${generated_tag}" &&
-          git pull --rebase &&
-          git push || true
-        if: steps.process_releases.outputs.generated_tag
+[[ if .HasDesktopFile ]]
+pkg_postinst() {
+  xdg_desktop_database_update
+}
+[[ end ]]
diff --git a/templates/github-binary.tmpl b/templates/github-binary.tmpl
--- a/templates/github-binary.tmpl
+++ b/templates/github-binary.tmpl
@@ -1,261 +1,119 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder [[.Version]] [[.Type]] [[.ConfigFile]] [[.Now]]
+# Generated by arrans_binary_overlay_builder
+EAPI=8
+DESCRIPTION="[[ .Description ]]"
+HOMEPAGE="[[ .Homepage ]]"
+LICENSE="[[ .License ]]"
+SLOT="0"
+KEYWORDS="[[ .MaskedKeywords ]]"
+IUSE="[[ range $use, $archs := $.ReverseProgramsAsAlternatives]] [[ $use | UseFlagSafe ]][[ end ]][[ if $.HasManualPages ]] man[[ end ]][[ if $.HasDocuments ]] doc[[ end ]][[ range $shell := $.ShellCompletionShells ]] [[ $shell | UseFlagSafe ]][[ end ]]"
+REQUIRED_USE="[[ range $use, $archs := $.ReverseProgramsAsAlternatives]][[ $use | UseFlagSafe ]]? ( || ( [[ range $arch := $archs]][[ $arch ]] [[ end ]] ) ) [[ end ]]"
+DEPEND=""
+RDEPEND="[[ range $i, $dep := .MainDependencies]][[ $dep ]] [[ end ]][[ range $prog, $deps := .AlternativeDependencies]][[ if gt (len $deps) 0 ]] [[ $prog ]]? ( [[ range $dep := $deps]][[ $dep ]] [[ end ]] ) [[ end ]][[ end ]]"
+S="${WORKDIR}"
 
-name: [[ .WorkflowName ]]
+SRC_URI="
+[[ range $er := .ExternalResources ]]
+  [[ range $i, $uf := $er.MustHaveUseFlags ]][[ $uf | UseFlagSafe ]]? ( [[ end ]][[ range $i, $uf := $er.MustntHaveUseFlags ]]![[ $uf | UseFlagSafe ]]? ( [[ end ]]https://github.com/[[ $.GithubOwner ]]/[[ $.GithubRepo ]]/releases/download/[[ $.Tag ]]/[[ $er.ReleaseFilename | ebuildvardoublequoted ]] [[ range $i, $uf := $er.MustHaveUseFlags ]] ) [[ end ]][[ range $i, $uf := $er.MustntHaveUseFlags ]] ) [[ end ]]
+[[ end ]]
+"
 
-permissions:
-  contents: write
-
-on:
-  schedule:
-    - cron: '[[ .Cron ]]'
-  workflow_dispatch:
-  push:
-    paths:
-      - '.github/workflows/[[ .WorkflowFileName ]]'
-
-concurrency:
-  group: ci-${{ github.ref }}
-  cancel-in-progress: false
-
-env:
-  ecn: [[ .Category ]]
-  epn: [[ .PackageName ]]
-  description: [[ .Description | quoteStr ]]
-  homepage: [[ .Homepage  | quoteStr ]]
-  github_owner: [[ .GithubOwner ]]
-  github_repo: [[ .GithubRepo ]]
-  keywords: [[ .MaskedKeywords ]]
-  workflow_filename: [[ .WorkflowFileName ]]
-  [[- range $pname, $prog := .Programs ]]
-  [[- if $prog.HasDesktopFile ]]
-  [[ join (filterEmpty $pname "desktop_file" ) "_" ]]: '[[ $prog.DesktopFile ]]'
+src_unpack() {
+[[ range $er := .ExternalResources ]]
+  [[- if $er.Archived ]]
+    [[ $count := 0 ]]
+    if [[range $i, $uf := $er.MustHaveUseFlags]][[ if gt $count 0]] && [[ end ]][[ $count = 1 ]]use [[ $uf | UseFlagSafe ]][[end]][[range $i, $uf := $er.MustntHaveUseFlags]][[ if gt $count 0]] && [[ end ]][[ $count = 1 ]]! use [[ $uf | UseFlagSafe ]] [[end]]; then
+        unpack "${DISTDIR}/[[ $er.ReleaseFilename | ebuildvardoublequoted ]]"
+    fi
   [[- end ]]
-  [[ join (filterEmpty $pname "binary_installed_name" ) "_" ]]: '[[ $prog.InstalledFilename ]]'
-  [[- range $keyword, $binary := $prog.Binary ]]
-  [[- if gt (len $binary) 2 ]]
-  [[ join (filterEmpty $pname "binary_archived_name" $keyword) "_" ]]: '[[ index $binary 1 ]]'
-  [[- end ]]
-  [[ join (filterEmpty $pname "release_name" $keyword) "_" ]]: '[[ index $binary 0 | ebuildvardoublequoted ]]'
-  [[- end ]]
-  [[- end ]]
-
-jobs:
-  check-and-create-ebuild:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      - name: Set up Git
-        run: |
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-
-      - name: Install required tools
-        run: |
-            sudo apt-get update
-            sudo apt-get install -y wget jq coreutils
-            url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
-            echo "$url"
-            wget "${url}" -O /tmp/g2.deb
-            sudo dpkg -i /tmp/g2.deb
-            rm /tmp/g2.deb
-
-      - name: Process each release
-        id: process_releases
-        run: |
-          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
-          mkdir -p $ebuild_dir
-          declare -A releaseTypes=()
-          tags=$(curl -s  --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[].tag_name')
-[[- if .WorkaroundSemanticVersionWithoutV ]]
-          for tag in $tags; do
-            version="${tag}"
-[[- else ]]
-          for tag in $tags; do
-            version="${tag#[[- .WorkaroundTagPrefix ]]v}"
-            if [ "${version}" = "${tag}" ]; then
-                echo "$version == $tag so there is no [[- .WorkaroundTagPrefix ]] v removed skipping"
-                continue
-            fi
-[[- end ]]
-            originalVersion="${version}"
-[[- if .WorkaroundSemanticVersionPrereleaseHack1 ]]
-            version="$(echo "${version}" | sed 's/^\([0-9]\+\(\.[0-9]\+\)*\)\(-r[0-9]*\)\?\([-_]\(alpha\|beta\|rc\|p\)[0-9]*\)$/\1_\5\3/')"
-[[- end ]]
-            if ! echo "${version}" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
-                echo "tag / $version doesn't match regexp";
-                continue;
-            fi
-            releaseType="$(echo "${version}" | sed -n 's/^[^_]\+_\(alpha\|beta\|rc\|p[0-9]*\).*$/\1/p')"
-            if [[`[[ ! -v releaseTypes[${releaseType:=release}] ]]`]]; then
-                if [[`[[ -v releaseTypes[release] ]]`]]; then
-                  echo "Already have a newer main release: ${releaseTypes[release]}"
-                  continue
-                fi
-                releaseTypes[${releaseType:=release}]="${version}"
-            else
-                echo "Already have a newer ${releaseType:=release} release: ${releaseTypes[${releaseType:=release}]}"
-                continue
-            fi
-            ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}.ebuild"
-            if [ ! -f "$ebuild_file" ]; then
-
-              {
-                echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/${{ env.workflow_filename }}'
-                echo 'EAPI=8'
-                echo "DESCRIPTION=\"${{ env.description }}\""
-                echo "HOMEPAGE=\"${{ env.homepage }}\""
-                echo 'LICENSE="MIT"'
-                echo 'SLOT="0"'
-                echo 'KEYWORDS="${{ env.keywords }}"'
-                echo 'IUSE="[[- `` -]]
-                        [[- range $use, $archs := $.ReverseProgramsAsAlternatives]] [[$use | UseFlagSafe ]][[end]]
-                        [[- if $.HasManualPages ]] man[[end]]
-                        [[- if $.HasDocuments ]] doc[[end]]
-                        [[- range $i, $shell := $.ShellCompletionShells]] [[$shell | UseFlagSafe ]][[end]]
-                    [[- `` -]]"'
-                echo 'REQUIRED_USE="[[- `` -]]
-                    [[- range $use, $archs := $.ReverseProgramsAsAlternatives]][[$use | UseFlagSafe ]]? ( || ( [[range $i, $arch := $archs]][[$arch]] [[end]] ) ) [[end]]
-                    [[- `` -]]"'
-                echo 'DEPEND=""'
-                echo 'RDEPEND="[[range $i, $dep := .MainDependencies]][[$dep]] [[end]]
-[[- range $prog, $deps := .AlternativeDependencies]][[ if gt (len $deps) 0 ]][[$prog]]? ( [[range $i, $dep := $deps]][[$dep]] [[end]] ) [[end]][[end -]]
-                     "'
-                echo 'S="${WORKDIR}"'
-                echo ''
-[[- if .HasDesktopFile ]]
-                echo ''
-[[- end ]]
-                echo ''
-                echo 'SRC_URI="'
-[[- range $i, $externalResource := .ExternalResources ]]
-                echo "  [[range $i, $uf := .MustHaveUseFlags]][[ $uf | UseFlagSafe ]]? ( [[end]][[range $i, $uf := .MustntHaveUseFlags]]![[ $uf | UseFlagSafe ]]? ( [[end]] https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/[[- if $.WorkaroundSemanticVersionPrereleaseHack1 ]][[ $externalResource.ReleaseFilename | ebuildvardoublequotedSemanticVersionPrereleaseHack1 ]][[- else ]][[ $externalResource.ReleaseFilename | ebuildvardoublequoted ]][[- end ]] -> \${P}-[[ $externalResource.ReleaseFilename  | ebuildvardoublequoted ]] [[range $i, $uf := .MustHaveUseFlags]] ) [[end]][[range $i, $uf := .MustntHaveUseFlags]] ) [[ end ]] "
-[[- end ]]
-                echo '"'
-                echo ''
-                echo 'src_unpack() {'
-[[- range $i, $externalResource := .ExternalResources ]]
-  [[- if $externalResource.Archived ]]
-    [[- $count := 0 ]]
-                echo '  if [[range $i, $uf := .MustHaveUseFlags]][[ if gt $count 0]] && [[ end ]][[ $count = 1]]use [[ $uf | UseFlagSafe  ]][[end]][[range $i, $uf := .MustntHaveUseFlags]][[ if gt $count 0]] && [[ end ]][[ $count = 1]]! use [[ $uf | UseFlagSafe ]] [[end]]; then'
-                echo "    unpack \"\${DISTDIR}/\${P}-[[ $externalResource.ReleaseFilename | ebuildvardoublequoted ]]\" || die \"Can't unpack archive file\""
-                echo '  fi'
-  [[- end ]]
-[[- end ]]
-[[- if $.HasCompressedManualPages ]]
-                echo '  if use man; then'
-    [[- range $i, $mans := $.CompressedManualPages ]]
-        [[- if ne $mans.Keyword "" ]]
-                echo '    if use [[ $mans.Keyword ]]; then'
-            [[- range $i, $man := $mans.Grouped ]]
-                echo '      [[ $man.Decompressor ]] "[[ $man.SourceFilepath ]]" || die "Failed to decompress manual page [[ $man.DestinationFilename ]]"'
-            [[- end ]]
-                echo '    fi'
-        [[- else ]]
-            [[- range $i, $man := $mans.Grouped ]]
-                echo '    [[ $man.Decompressor ]] "[[ $man.SourceFilepath ]]" || die "Failed to decompress manual page [[ $man.DestinationFilename ]]"'
-            [[- end ]]
-        [[- end ]]
+[[ end ]]
+[[ if $.HasCompressedManualPages ]]
+  if use man; then
+    [[- range $mans := $.CompressedManualPages ]]
+      [[- if ne $mans.Keyword "" ]]
+    if use [[ $mans.Keyword ]]; then
+      [[- range $man := $mans.Grouped ]]
+        [[ $man.Decompressor ]] "[[ $man.SourceFilepath ]]" || die "Failed to decompress manual page [[ $man.DestinationFilename ]]"
+      [[- end ]]
+    fi
+      [[- else ]]
+      [[- range $man := $mans.Grouped ]]
+        [[ $man.Decompressor ]] "[[ $man.SourceFilepath ]]" || die "Failed to decompress manual page [[ $man.DestinationFilename ]]"
+      [[- end ]]
+      [[- end ]]
     [[- end ]]
-                echo '  fi'
-[[- end ]]
-                echo '}'
-                echo ''
-                echo 'src_install() {'
-                echo '  exeinto /opt/bin'
+  fi
+[[ end ]]
+}
 
-[[- range $pname, $prog := .Programs ]]
-  [[- range $keyword, $binary := $prog.Binary ]]
-    [[- if gt (len $binary) 2 ]]
-        [[- $count := 0 ]]
-                echo '  if [[range $i, $uf := $.GetMustHaveUseFlags $pname $keyword ]][[ if gt $count 0]] && [[ end ]][[ $count = 1]]use [[ $uf | UseFlagSafe ]][[end]][[range $i, $uf := $.GetMustntHaveUseFlags $pname $keyword ]][[ if gt $count 0]] && [[ end ]][[ $count = 1]]! use [[ $uf | UseFlagSafe ]] [[end]]; then'
-                echo '    newexe "${{ env.[[ join (filterEmpty $pname "binary_archived_name" $keyword) "_" ]] }}" "${{ env.[[ join (filterEmpty $pname "binary_installed_name" ) "_" ]] }}" || die "Failed to install Binary"'
-                echo '  fi'
-    [[- else ]]
-        [[- $count := 0 ]]
-                echo '  if [[range $i, $uf := $.GetMustHaveUseFlags $pname $keyword ]][[ if gt $count 0]] && [[ end ]][[ $count = 1]]use [[ $uf ]][[end]][[range $i, $uf := $.GetMustntHaveUseFlags $pname $keyword ]][[ if gt $count 0]] && [[ end ]][[ $count = 1]]! use [[ $uf ]] [[end]]; then'
-                echo '    newexe "${DISTDIR}/${P}-${{ env.[[ join (filterEmpty $pname "release_name" $keyword) "_" ]] }}" "${{ env.[[ join (filterEmpty $pname "binary_installed_name" ) "_" ]] }}" || die "Failed to install Binary"'
-                echo '  fi'
+src_install() {
+    exeinto /opt/bin
+[[ range $pname, $prog := .Programs ]]
+[[ range $keyword, $binary := $prog.Binary ]]
+[[ if gt (len $binary) 2 ]]
+    [[ $count := 0 ]]
+    if [[range $i, $uf := $.GetMustHaveUseFlags $pname $keyword]][[ if gt $count 0]] && [[ end ]][[ $count = 1 ]]use [[ $uf | UseFlagSafe ]][[end]][[range $i, $uf := $.GetMustntHaveUseFlags $pname $keyword]][[ if gt $count 0]] && [[ end ]][[ $count = 1 ]]! use [[ $uf | UseFlagSafe ]] [[end]]; then
+        newexe "[[ index $binary 1 ]]" "[[ $prog.InstalledFilename ]]" || die "Failed to install binary"
+    fi
+[[ else ]]
+    [[ $count := 0 ]]
+    if [[range $i, $uf := $.GetMustHaveUseFlags $pname $keyword]][[ if gt $count 0]] && [[ end ]][[ $count = 1 ]]use [[ $uf | UseFlagSafe ]][[end]][[range $i, $uf := $.GetMustntHaveUseFlags $pname $keyword]][[ if gt $count 0]] && [[ end ]][[ $count = 1 ]]! use [[ $uf | UseFlagSafe ]] [[end]]; then
+        newexe "${DISTDIR}/[[ index $binary 0 | ebuildvardoublequoted ]]" "[[ $prog.InstalledFilename ]]" || die "Failed to install binary"
+    fi
+[[ end ]]
+[[ end ]]
+[[ end ]]
+
+[[ range $shell := $.ShellCompletionShells ]]
+  if use [[ $shell ]]; then
+    insinto "[[ $.ShellCompletionInstallPath $shell ]]"
+    [[- range $files := $.ShellCompletion $shell ]]
+      [[- if ne $files.Keyword "" ]]
+    if use [[ $files.Keyword ]]; then
+      [[- range $file := $files.Grouped ]]
+        newins "[[ $file.SourceFilepath ]]" "[[ $file.DestinationFilename ]]" || die "Failed to shell completion file"
+      [[- end ]]
+    fi
+      [[- else ]]
+      [[- range $file := $files.Grouped ]]
+        newins "[[ $file.SourceFilepath ]]" "[[ $file.DestinationFilename ]]" || die "Failed to shell completion file"
+      [[- end ]]
+      [[- end ]]
     [[- end ]]
-  [[- end ]]
-[[- end ]]
+  fi
+[[ end ]]
 
-
-[[- range $i, $shell := $.ShellCompletionShells]]
-                echo '  if use [[ $shell ]]; then'
-                echo '    insinto "[[ $.ShellCompletionInstallPath $shell ]]"'
-    [[- range $i, $files := $.ShellCompletion $shell ]]
-        [[- if ne $files.Keyword "" ]]
-                echo '    if use [[ $files.Keyword ]]; then'
-            [[- range $i, $file := $files.Grouped ]]
-                echo '      newins "[[ $file.SourceFilepath ]]" "[[ $file.DestinationFilename ]]" || die "Failed to bash completion file"'
-            [[- end ]]
-                echo '    fi'
-        [[- else ]]
-            [[- range $i, $file := $files.Grouped ]]
-                echo '    newins "[[ $file.SourceFilepath ]]" "[[ $file.DestinationFilename ]]" || die "Failed to bash completion file"'
-            [[- end ]]
-        [[- end ]]
+[[ if $.HasManualPages ]]
+  if use man; then
+    [[- range $mans := $.ManualPages ]]
+      [[- if ne $mans.Keyword "" ]]
+    if use [[ $mans.Keyword ]]; then
+      [[- range $man := $mans.Grouped ]]
+        newman "[[ $man.UncompressedSourceFilepath ]]" "[[ $man.DestinationFilename ]]" || die "Failed to install manual page [[ $man.DestinationFilename ]]"
+      [[- end ]]
+    fi
+      [[- else ]]
+      [[- range $man := $mans.Grouped ]]
+        newman "[[ $man.UncompressedSourceFilepath ]]" "[[ $man.DestinationFilename ]]" || die "Failed to install manual page [[ $man.DestinationFilename ]]"
+      [[- end ]]
+      [[- end ]]
     [[- end ]]
-                echo '  fi'
-[[- end ]]
-[[- if $.HasManualPages ]]
-                echo '  if use man; then'
-    [[- range $i, $mans := $.ManualPages ]]
-        [[- if ne $mans.Keyword "" ]]
-                echo '    if use [[ $mans.Keyword ]]; then'
-            [[- range $i, $man := $mans.Grouped ]]
-                echo '      newman "[[ $man.UncompressedSourceFilepath ]]" "[[ $man.DestinationFilename ]]" || die "Failed to install manual page [[ $man.DestinationFilename ]]"'
-            [[- end ]]
-                echo '    fi'
-        [[- else ]]
-            [[- range $i, $man := $mans.Grouped ]]
-                echo '    newman "[[ $man.UncompressedSourceFilepath ]]" "[[ $man.DestinationFilename ]]" || die "Failed to install manual page [[ $man.DestinationFilename ]]"'
-            [[- end ]]
-        [[- end ]]
+  fi
+[[ end ]]
+[[ if $.HasDocuments ]]
+  if use doc; then
+    [[- range $docs := $.Documents ]]
+      [[- if ne $docs.Keyword "" ]]
+    if use [[ $docs.Keyword ]]; then
+      [[- range $doc := $docs.Grouped ]]
+        newdoc "[[ $doc.SourceFilepath ]]" "[[ $doc.DestinationFilename ]]" || die "Failed to install document [[ $doc.DestinationFilename ]]"
+      [[- end ]]
+    fi
+      [[- else ]]
+      [[- range $doc := $docs.Grouped ]]
+        newdoc "[[ $doc.SourceFilepath ]]" "[[ $doc.DestinationFilename ]]" || die "Failed to install document [[ $doc.DestinationFilename ]]"
+      [[- end ]]
+      [[- end ]]
     [[- end ]]
-                echo '  fi'
-[[- end ]]
-[[- if $.HasDocuments ]]
-                echo '  if use doc; then'
-    [[- range $i, $docs := $.Documents ]]
-        [[- if ne $docs.Keyword "" ]]
-                echo '    if use [[ $docs.Keyword ]]; then'
-            [[- range $ii, $doc := $docs.Grouped ]]
-                echo '      newdoc "[[ $doc.SourceFilepath ]]" "[[ $doc.DestinationFilename ]]" || die "Failed to install document [[ $doc.DestinationFilename ]]"'
-            [[- end ]]
-                echo '    fi'
-        [[- else ]]
-            [[- range $ii, $doc := $docs.Grouped ]]
-                echo '    newdoc "[[ $doc.SourceFilepath ]]" "[[ $doc.DestinationFilename ]]" || die "Failed to install document [[ $doc.DestinationFilename ]]"'
-            [[- end ]]
-        [[- end ]]
-    [[- end ]]
-                echo '  fi'
-[[- end ]]
-                echo '}'
-                echo ""
-              } > $ebuild_file
-
-              # Manifest generation
-[[ range $i, $externalResource := .ExternalResources ]]
-    [[- if $.WorkaroundSemanticVersionPrereleaseHack1 ]]
-              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/[[ $externalResource.ReleaseFilename | ebuildvardoublequotedSemanticVersionPrereleaseHack1 ]]" "${{ env.epn }}-${version}-[[ $externalResource.ReleaseFilename | actionvardoublequoted ]]" "${ebuild_dir}/Manifest"
-    [[- else ]]
-              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/[[ $externalResource.ReleaseFilename | actionvardoublequoted ]]" "${{ env.epn }}-${version}-[[ $externalResource.ReleaseFilename | actionvardoublequoted ]]" "${ebuild_dir}/Manifest"
-    [[- end ]]
-
-[[- end ]]
-              echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
-            fi
-          done
-
-      - name: Commit and push changes
-        run: |
-          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
-          git add ./${ebuild_dir}
-          git commit -m "Add ebuilds for new ${{ env.epn }} releases tag ${generated_tag}" &&
-          git pull --rebase &&
-          git push || true
-        if: steps.process_releases.outputs.generated_tag
+  fi
+[[ end ]]
+}
