Test again

diff --git a/.github/workflows/app-misc-localsend-appimage-update.yaml b/.github/workflows/app-misc-localsend-appimage-update.yaml
--- a/.github/workflows/app-misc-localsend-appimage-update.yaml
+++ b/.github/workflows/app-misc-localsend-appimage-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage testdata/testinputconfig.config 2024-07-13 19:45:54.083587603 +1000 AEST m=+0.001091763
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage testdata/testinputconfig.config 2024-07-13 19:51:49.025156192 +1000 AEST m=+0.001069960
 
 name: app-misc/localsend-appimage update
 
@@ -96,7 +96,7 @@ jobs:
                 echo "    unpack \"\${DISTDIR}/\${P}-LocalSend-1.14.0-linux-x86-64.AppImage\" || die \"Can't unpack archive file\""
                 echo '  fi'
                 echo '  if use amd64; then'
-                echo "    cp \"\${DISTDIR}/${{ env.localsend_release_name_amd64 }}\" \"${{ env.localsend_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
+                echo "    cp \"\${DISTDIR}/\${P}-${{ env.localsend_release_name_amd64 }}\" \"${{ env.localsend_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
                 echo '  fi'
                 echo '  chmod a+x "${{ env.localsend_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
                 echo '  ./${{ env.localsend_appimage_installed_name }} --appimage-extract "${{ env.localsend_desktop_file }}" || die "Failed to extract .desktop from appimage"'
diff --git a/templates/github-appimage.tmpl b/templates/github-appimage.tmpl
--- a/templates/github-appimage.tmpl
+++ b/templates/github-appimage.tmpl
@@ -116,13 +116,13 @@ jobs:
 [[- if .IsArchived ]]
   [[- range $keyword, $archive := $prog.ArchiveFilename ]]
                 echo '  if use [[ $keyword ]]; then'
-                echo '    mv "${DESTDIR}/${{ env.[[ join (filterEmpty $pname "appimage_archived_name" ) "_" ]] }}" "${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}"  || die "Can'\''t move archived file"'
+                echo '    mv "${DESTDIR}/\${P}-${{ env.[[ join (filterEmpty $pname "appimage_archived_name" $keyword) "_" ]] }}" "${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}"  || die "Can'\''t move archived file"'
                 echo '  fi'
   [[- end ]]
 [[- else ]]
   [[- range $keyword, $release := $prog.ReleasesFilename ]]
                 echo '  if use [[ $keyword ]]; then'
-                echo "    cp \"\${DISTDIR}/${{ env.[[ join (filterEmpty $pname "release_name" $keyword) "_" ]] }}\" \"${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}\"  || die \"Can't copy downloaded file\""
+                echo "    cp \"\${DISTDIR}/\${P}-${{ env.[[ join (filterEmpty $pname "release_name" $keyword) "_" ]] }}\" \"${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}\"  || die \"Can't copy downloaded file\""
                 echo '  fi'
   [[- end ]]
 [[- end ]]
