Again

diff --git a/.github/workflows/app-misc-StabilityMatrix-appimage-update.yaml b/.github/workflows/app-misc-StabilityMatrix-appimage-update.yaml
--- a/.github/workflows/app-misc-StabilityMatrix-appimage-update.yaml
+++ b/.github/workflows/app-misc-StabilityMatrix-appimage-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage testdata/testinputconfig.config 2024-07-13 19:51:49.025156192 +1000 AEST m=+0.001069960
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage testdata/testinputconfig.config 2024-07-14 00:13:51.957334334 +1000 AEST m=+0.001057096
 
 name: app-misc/StabilityMatrix-appimage update
 
@@ -97,7 +97,7 @@ jobs:
                 echo "    unpack \"\${DISTDIR}/\${P}-StabilityMatrix-linux-x64.zip\" || die \"Can't unpack archive file\""
                 echo '  fi'
                 echo '  if use amd64; then'
-                echo '    mv "${DESTDIR}/\${P}-${{ env.StabilityMatrix_appimage_archived_name_amd64 }}" "${{ env.StabilityMatrix_appimage_installed_name }}"  || die "Can'\''t move archived file"'
+                echo "    mv \"\${DESTDIR}/\${P}-${{ env.StabilityMatrix_appimage_archived_name_amd64 }}\" \"${{ env.StabilityMatrix_appimage_installed_name }}\"  || die \"Can't move archived file\""
                 echo '  fi'
                 echo '  chmod a+x "${{ env.StabilityMatrix_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
                 echo '  ./${{ env.StabilityMatrix_appimage_installed_name }} --appimage-extract "${{ env.StabilityMatrix_desktop_file }}" || die "Failed to extract .desktop from appimage"'
@@ -107,7 +107,7 @@ jobs:
                 echo 'src_prepare() {'
                 echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.StabilityMatrix_appimage_installed_name }}:' 'squashfs-root/${{ env.StabilityMatrix_desktop_file }}'"
                 echo "  find squashfs-root -type f \( -name index.theme -or -name icon-theme.cache \) -exec rm {} \; "
-                echo "  find squashfs-root -type d -exec rmdir -p {} \; "
+                echo "  find squashfs-root -type d -exec rmdir -p --ignore-fail-on-non-empty {} \; "
                 echo '  eapply_user'
                 echo '}'
                 echo ''
diff --git a/templates/github-appimage.tmpl b/templates/github-appimage.tmpl
--- a/templates/github-appimage.tmpl
+++ b/templates/github-appimage.tmpl
@@ -118,7 +118,7 @@ jobs:
 [[- if .IsArchived ]]
   [[- range $keyword, $archive := $prog.ArchiveFilename ]]
                 echo '  if use [[ $keyword ]]; then'
-                echo '    mv "${DESTDIR}/\${P}-${{ env.[[ join (filterEmpty $pname "appimage_archived_name" $keyword) "_" ]] }}" "${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}"  || die "Can'\''t move archived file"'
+                echo "    mv \"\${DESTDIR}/\${P}-${{ env.[[ join (filterEmpty $pname "appimage_archived_name" $keyword) "_" ]] }}\" \"${{ env.[[ join (filterEmpty $pname "appimage_installed_name" ) "_" ]] }}\"  || die \"Can't move archived file\""
                 echo '  fi'
   [[- end ]]
 [[- else ]]
