Ah yeah we already know the name.

diff --git a/.github/workflows/app-misc-StabilityMatrix-appimage-update.yaml b/.github/workflows/app-misc-StabilityMatrix-appimage-update.yaml
--- a/.github/workflows/app-misc-StabilityMatrix-appimage-update.yaml
+++ b/.github/workflows/app-misc-StabilityMatrix-appimage-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage testdata/testinputconfig.config 2024-07-14 00:19:47.306938396 +1000 AEST m=+0.001075487
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage testdata/testinputconfig.config 2024-07-14 00:22:47.906912922 +1000 AEST m=+0.001080700
 
 name: app-misc/StabilityMatrix-appimage update
 
@@ -97,7 +97,7 @@ jobs:
                 echo "    unpack \"\${DISTDIR}/\${P}-StabilityMatrix-linux-x64.zip\" || die \"Can't unpack archive file\""
                 echo '  fi'
                 echo '  if use amd64; then'
-                echo "    mv \"\${P}-${{ env.StabilityMatrix_appimage_archived_name_amd64 }}\" \"${{ env.StabilityMatrix_appimage_installed_name }}\"  || die \"Can't move archived file\""
+                echo "    mv \"${{ env.StabilityMatrix_appimage_archived_name_amd64 }}\" \"${{ env.StabilityMatrix_appimage_installed_name }}\"  || die \"Can't move archived file\""
                 echo '  fi'
                 echo '  chmod a+x "${{ env.StabilityMatrix_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
                 echo '  ./${{ env.StabilityMatrix_appimage_installed_name }} --appimage-extract "${{ env.StabilityMatrix_desktop_file }}" || die "Failed to extract .desktop from appimage"'
