Test 2.

diff --git a/.github/workflows/app-misc-lemmy-notify-appimage-update.yaml b/.github/workflows/app-misc-lemmy-notify-appimage-update.yaml
--- a/.github/workflows/app-misc-lemmy-notify-appimage-update.yaml
+++ b/.github/workflows/app-misc-lemmy-notify-appimage-update.yaml
@@ -1,17 +1,17 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage testdata/testinputconfig.config 2024-07-14 00:39:11.208581427 +1000 AEST m=+0.001097022
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage testdata/testinputconfig.config 2024-07-14 00:52:29.84329649 +1000 AEST m=+0.001076478
 
-name: app-misc/caprine-appimage update
+name: app-misc/lemmy-notify-appimage update
 
 permissions:
   contents: write
 
 on:
   schedule:
-    - cron: '18 12 * * *'
+    - cron: '48 21 * * *'
   workflow_dispatch:
   push:
     paths:
-      - '.github/workflows/app-misc-caprine-appimage-update.yaml'
+      - '.github/workflows/app-misc-lemmy-notify-appimage-update.yaml'
 
 concurrency:
   group: ci-${{ github.ref }}
@@ -19,16 +19,16 @@ concurrency:
 
 env:
   ecn: app-misc
-  epn: caprine-appimage
-  description: "Elegant Facebook Messenger desktop app"
-  homepage: "https://sindresorhus.com/caprine"
-  github_owner: sindresorhus
-  github_repo: caprine
+  epn: lemmy-notify-appimage
+  description: "Lemmy Notification app - for desktop atm"
+  homepage: ""
+  github_owner: arran4
+  github_repo: lemmy_notify
   keywords: ~amd64
-  workflow_filename: app-misc-caprine-appimage-update.yaml
-  Caprine_desktop_file: 'caprine.desktop'
-  Caprine_appimage_installed_name: 'Caprine.AppImage'
-  Caprine_release_name_amd64: 'Caprine-2.60.1.AppImage'
+  workflow_filename: app-misc-lemmy-notify-appimage-update.yaml
+  lemmy_notify_desktop_file: 'lemmy_notify.desktop'
+  lemmy_notify_appimage_installed_name: 'lemmy_notify.AppImage'
+  lemmy_notify_release_name_amd64: 'lemmy_notify-linux-x86_64.AppImage'
 
 jobs:
   check-and-create-ebuild:
@@ -88,20 +88,20 @@ jobs:
                 echo "inherit xdg-utils"
                 echo ''
                 echo 'SRC_URI="'
-                echo "  amd64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/Caprine-2.60.1.AppImage -> \${P}-Caprine-2.60.1.AppImage )"
+                echo "  amd64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/lemmy_notify-linux-x86_64.AppImage -> \${P}-lemmy_notify-linux-x86_64.AppImage )"
                 echo '"'
                 echo ''
                 echo 'src_unpack() {'
                 echo '  if use amd64; then'
-                echo "    cp \"\${DISTDIR}/\${P}-${{ env.Caprine_release_name_amd64 }}\" \"${{ env.Caprine_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
+                echo "    cp \"\${DISTDIR}/\${P}-${{ env.lemmy_notify_release_name_amd64 }}\" \"${{ env.lemmy_notify_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
                 echo '  fi'
-                echo '  chmod a+x "${{ env.Caprine_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
-                echo '  ./${{ env.Caprine_appimage_installed_name }} --appimage-extract "${{ env.Caprine_desktop_file }}" || die "Failed to extract .desktop from appimage"'
-                echo '  ./${{ env.Caprine_appimage_installed_name }} --appimage-extract "usr/share/icons" || die "Failed to extract icons from app image"'
+                echo '  chmod a+x "${{ env.lemmy_notify_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
+                echo '  ./${{ env.lemmy_notify_appimage_installed_name }} --appimage-extract "${{ env.lemmy_notify_desktop_file }}" || die "Failed to extract .desktop from appimage"'
+                echo '  ./${{ env.lemmy_notify_appimage_installed_name }} --appimage-extract "usr/share/icons" || die "Failed to extract icons from app image"'
                 echo '}'
                 echo ''
                 echo 'src_prepare() {'
-                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.Caprine_appimage_installed_name }}:' 'squashfs-root/${{ env.Caprine_desktop_file }}'"
+                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.lemmy_notify_appimage_installed_name }}:' 'squashfs-root/${{ env.lemmy_notify_desktop_file }}'"
                 echo "  find squashfs-root -type f \( -name index.theme -or -name icon-theme.cache \) -exec rm {} \; "
                 echo "  find squashfs-root -type d -exec rmdir -p --ignore-fail-on-non-empty {} \; "
                 echo '  eapply_user'
@@ -109,9 +109,9 @@ jobs:
                 echo ''
                 echo 'src_install() {'
                 echo '  exeinto /opt/bin'
-                echo '  doexe "${{ env.Caprine_appimage_installed_name }}" || die "Failed to install AppImage"'
+                echo '  doexe "${{ env.lemmy_notify_appimage_installed_name }}" || die "Failed to install AppImage"'
                 echo '  insinto /usr/share/applications'
-                echo '  doins "squashfs-root/${{ env.Caprine_desktop_file }}" || die "Failed to install desktop file"'
+                echo '  doins "squashfs-root/${{ env.lemmy_notify_desktop_file }}" || die "Failed to install desktop file"'
                 echo '  insinto /usr/share/icons'
                 echo '  doins -r squashfs-root/usr/share/icons/hicolor || die "Failed to install icons"'
                 echo '}'
@@ -124,7 +124,7 @@ jobs:
 
               # Manifest generation
                
-              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/Caprine-2.60.1.AppImage" "${{ env.epn }}-${version}-Caprine-2.60.1.AppImage" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/lemmy_notify-linux-x86_64.AppImage" "${{ env.epn }}-${version}-lemmy_notify-linux-x86_64.AppImage" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
             break
diff --git a/.github/workflows/net-im-caprine-appimage-update.yaml b/.github/workflows/net-im-caprine-appimage-update.yaml
--- a/.github/workflows/net-im-caprine-appimage-update.yaml
+++ b/.github/workflows/net-im-caprine-appimage-update.yaml
@@ -1,35 +1,34 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage testdata/testinputconfig.config 2024-07-14 00:39:11.208581427 +1000 AEST m=+0.001097022
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage testdata/testinputconfig.config 2024-07-14 00:52:29.84329649 +1000 AEST m=+0.001076478
 
-name: app-misc/chatbox-appimage update
+name: net-im/caprine-appimage update
 
 permissions:
   contents: write
 
 on:
   schedule:
-    - cron: '25 12 * * *'
+    - cron: '18 12 * * *'
   workflow_dispatch:
   push:
     paths:
-      - '.github/workflows/app-misc-chatbox-appimage-update.yaml'
+      - '.github/workflows/net-im-caprine-appimage-update.yaml'
 
 concurrency:
   group: ci-${{ github.ref }}
   cancel-in-progress: false
 
 env:
-  ecn: app-misc
-  epn: chatbox-appimage
-  description: "User-friendly Desktop Client App for AI Models/LLMs (GPT, Claude, Gemini, Ollama...)"
-  homepage: "https://chatboxai.app"
-  github_owner: Bin-Huang
-  github_repo: chatbox
-  keywords: ~amd64 ~arm64
-  workflow_filename: app-misc-chatbox-appimage-update.yaml
-  Chatbox_desktop_file: 'xyz.chatboxapp.app.desktop'
-  Chatbox_appimage_installed_name: 'Chatbox.AppImage'
-  Chatbox_release_name_amd64: 'Chatbox-1.3.10-x86_64.AppImage'
-  Chatbox_release_name_arm64: 'Chatbox-1.3.10-arm64.AppImage'
+  ecn: net-im
+  epn: caprine-appimage
+  description: "Elegant Facebook Messenger desktop app"
+  homepage: "https://sindresorhus.com/caprine"
+  github_owner: sindresorhus
+  github_repo: caprine
+  keywords: ~amd64
+  workflow_filename: net-im-caprine-appimage-update.yaml
+  Caprine_desktop_file: 'caprine.desktop'
+  Caprine_appimage_installed_name: 'Caprine.AppImage'
+  Caprine_release_name_amd64: 'Caprine-2.60.1.AppImage'
 
 jobs:
   check-and-create-ebuild:
@@ -89,24 +88,20 @@ jobs:
                 echo "inherit xdg-utils"
                 echo ''
                 echo 'SRC_URI="'
-                echo "  arm64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/Chatbox-1.3.10-arm64.AppImage -> \${P}-Chatbox-1.3.10-arm64.AppImage )"
-                echo "  amd64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/Chatbox-1.3.10-x86_64.AppImage -> \${P}-Chatbox-1.3.10-x86_64.AppImage )"
+                echo "  amd64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/Caprine-2.60.1.AppImage -> \${P}-Caprine-2.60.1.AppImage )"
                 echo '"'
                 echo ''
                 echo 'src_unpack() {'
                 echo '  if use amd64; then'
-                echo "    cp \"\${DISTDIR}/\${P}-${{ env.Chatbox_release_name_amd64 }}\" \"${{ env.Chatbox_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
+                echo "    cp \"\${DISTDIR}/\${P}-${{ env.Caprine_release_name_amd64 }}\" \"${{ env.Caprine_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
                 echo '  fi'
-                echo '  if use arm64; then'
-                echo "    cp \"\${DISTDIR}/\${P}-${{ env.Chatbox_release_name_arm64 }}\" \"${{ env.Chatbox_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
-                echo '  fi'
-                echo '  chmod a+x "${{ env.Chatbox_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
-                echo '  ./${{ env.Chatbox_appimage_installed_name }} --appimage-extract "${{ env.Chatbox_desktop_file }}" || die "Failed to extract .desktop from appimage"'
-                echo '  ./${{ env.Chatbox_appimage_installed_name }} --appimage-extract "usr/share/icons" || die "Failed to extract icons from app image"'
+                echo '  chmod a+x "${{ env.Caprine_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
+                echo '  ./${{ env.Caprine_appimage_installed_name }} --appimage-extract "${{ env.Caprine_desktop_file }}" || die "Failed to extract .desktop from appimage"'
+                echo '  ./${{ env.Caprine_appimage_installed_name }} --appimage-extract "usr/share/icons" || die "Failed to extract icons from app image"'
                 echo '}'
                 echo ''
                 echo 'src_prepare() {'
-                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.Chatbox_appimage_installed_name }}:' 'squashfs-root/${{ env.Chatbox_desktop_file }}'"
+                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.Caprine_appimage_installed_name }}:' 'squashfs-root/${{ env.Caprine_desktop_file }}'"
                 echo "  find squashfs-root -type f \( -name index.theme -or -name icon-theme.cache \) -exec rm {} \; "
                 echo "  find squashfs-root -type d -exec rmdir -p --ignore-fail-on-non-empty {} \; "
                 echo '  eapply_user'
@@ -114,9 +109,9 @@ jobs:
                 echo ''
                 echo 'src_install() {'
                 echo '  exeinto /opt/bin'
-                echo '  doexe "${{ env.Chatbox_appimage_installed_name }}" || die "Failed to install AppImage"'
+                echo '  doexe "${{ env.Caprine_appimage_installed_name }}" || die "Failed to install AppImage"'
                 echo '  insinto /usr/share/applications'
-                echo '  doins "squashfs-root/${{ env.Chatbox_desktop_file }}" || die "Failed to install desktop file"'
+                echo '  doins "squashfs-root/${{ env.Caprine_desktop_file }}" || die "Failed to install desktop file"'
                 echo '  insinto /usr/share/icons'
                 echo '  doins -r squashfs-root/usr/share/icons/hicolor || die "Failed to install icons"'
                 echo '}'
@@ -129,8 +124,7 @@ jobs:
 
               # Manifest generation
                
-              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/Chatbox-1.3.10-arm64.AppImage" "${{ env.epn }}-${version}-Chatbox-1.3.10-arm64.AppImage" "${ebuild_dir}/Manifest" 
-              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/Chatbox-1.3.10-x86_64.AppImage" "${{ env.epn }}-${version}-Chatbox-1.3.10-x86_64.AppImage" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/Caprine-2.60.1.AppImage" "${{ env.epn }}-${version}-Caprine-2.60.1.AppImage" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
             break
